### ISSUE TITLE
LoRa IC - Could only find  breakout board

### ISSUE THREAD

**Issue by mitchellciupak** [ECE477/Hardwear-Design#11]
This is the only thing we can find to buy, but we just want the chip off it
https://www.digikey.com/en/products/detail/rf-solutions/rfm95w-868s2/5051755

IF FIXED UPDATE
https://github.com/ECE477/Hardwear-Design/wiki/Primary-Component-Footprint-Assignments

**Comment by ckemmet** [comment]
This is fine. The whole SMD module should be used, and that's the footprint that we have.
