### ISSUE TITLE
Schematic Fixes

### ISSUE THREAD

**Issue by monacok21** [ECE477/Hardwear-Design#16]
1. Add 100ohm resistors in series to Micro to avoid shocking users
2. Remove GPS LED to avoid unnecessary current draw
3. Fix Flag Labels
4. Use Qwiic connector for OLED
5. Replace 1 pin headers with 2 pin - need ground reference

**Comment by ckemmet** [comment]
1. Fixed with "schematic issue partial fix" commit
2. Deemed unnecessary, we can choose to drive it or not
3. Kennedy fixed earlier
4. Needs fixing
5. Fixed with "schematic issue partial fix" commit

**Comment by ckemmet** [comment]
Making a separate issue for one remaining item (step 4)
