### ISSUE TITLE
TOLED - Can we just supply pinout to breakout board? 

### ISSUE THREAD

**Issue by mitchellciupak** [ECE477/Hardwear-Design#8]
Given that the TOLED is not placed near the PCB we have decided to provide pin headers in our design that will be connected to the Sparkfun breakout 

We should consult the course staff on this decision 

Datasheet in this repos wiki
https://github.com/ECE477/Hardwear-Design/wiki

Hookup Guide
https://learn.sparkfun.com/tutorials/transparent-graphical-oled-breakout-hookup-guide?_ga=2.116312454.1468728622.1602081205-1154625250.1599761813

Product Page
https://www.sparkfun.com/products/15173

**Comment by monacok21** [comment]
Agreed. We just need to be sure that the jumpers are properly severed to use SPI mode.
