### ISSUE TITLE
IMU PS1/Pin5 routed to VDDIO? *Need Confrim

### ISSUE THREAD

**Issue by mitchellciupak** [ECE477/Hardwear-Design#9]
Data Sheet page 98 https://learn.adafruit.com/bno055-absolute-orientation-sensor-with-raspberry-pi-and-beaglebone-black/hardware

Hookup Guide: https://learn.adafruit.com/bno055-absolute-orientation-sensor-with-raspberry-pi-and-beaglebone-black/hardware

**Comment by monacok21** [comment]
No, according to the datasheet PS1 and PS0 should be connected to GND for I2C mode.
![image](https://user-images.githubusercontent.com/35317831/95394486-9fa8fc00-08ca-11eb-8dba-4f3f5c651ac8.png)

**Comment by mitchellciupak** [comment]
Looks updated correctly in schematic and pcb file. Thanks @monacok21
